name: Checkout the code

on: workflow_dispatch

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v7
        
        uses: actions/checkout@v3
      - name: list the files
        run: ls -lart